In [32]:
import pandas as pd
df = pd.read_csv('data-bug.csv')

In [34]:
idx = 0
for column in df:
    if "correct_answer" in column:
        if "numeric-line" in column:
            new_column = df[column] == df[f"{column[:-14]}user_answer"]
            df[f"{column[:-14]}user_score"] = new_column
    idx += 1

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3361: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  if (await self.run_code(code, result,  async_=asy)):

In [32]:
df

,alias,dots-comparison_RT,dots-comparison_accuracy,dots-comparison_IES,dots-comparison_1_correct_answer,dots-comparison_1_user_answer,dots-comparison_1_user_score,dots-comparison_1_time,dots-comparison_2_correct_answer,dots-comparison_2_user_score,...,simple-arithmetic-minus_17_time,simple-arithmetic-minus_18_correct_answer,simple-arithmetic-minus_18_user_answer,simple-arithmetic-minus_18_time,simple-arithmetic-minus_19_correct_answer,simple-arithmetic-minus_19_user_answer,simple-arithmetic-minus_19_time,simple-arithmetic-minus_20_correct_answer,simple-arithmetic-minus_20_user_answer,simple-arithmetic-minus_20_time
0,Test 1,"1283,3",1,"1283,3",4.0,4.0,True,1074.0,8.0,True,...,1342.0,2.0,2.0,1535.0,1.0,1.0,1148.0,1.0,1.0,1823.0
1,CataP,"1800,1",1,"1800,1",9.0,9.0,True,1639.0,9.0,True,...,3724.0,1.0,1.0,2450.0,2.0,2.0,3617.0,2.0,2.0,1709.0
2,prueba 1,4099,1,4099,10.0,10.0,True,2361.0,6.0,True,...,3503.0,3.0,3.0,4578.0,1.0,1.0,3686.0,0.0,0.0,3194.0
3,Ines,"1074,2",1,"1074,2",8.0,8.0,True,1232.0,6.0,True,...,753.0,0.0,6.0,617.0,1.0,1.0,830.0,0.0,3.0,734.0
4,Prueba 5 (MZ),"9250,6",1,"9250,6",6.0,6.0,True,6294.0,9.0,True,...,8860.0,3.0,3.0,10101.0,3.0,3.0,5951.0,1.0,1.0,4803.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,RAMAG,"1979,9",1,"1979,9",10.0,10.0,True,1888.0,5.0,True,...,4092.0,1.0,3.0,3353.0,5.0,8.0,5310.0,4.0,7.0,4421.0
109,PETMI,"1779,1","0,9","1976,777778",9.0,9.0,True,1604.0,9.0,True,...,9645.0,4.0,4.0,9616.0,4.0,4.0,10986.0,4.0,4.0,10998.0
110,SAULO,"2950,2",1,"2950,2",8.0,8.0,True,4326.0,9.0,True,...,1169.0,4.0,2.0,1287.0,7.0,8.0,2384.0,3.0,3.0,1255.0
111,ZUNMA,"5434,2",1,"5434,2",8.0,8.0,True,7974.0,6.0,True,...,10819.0,1.0,5.0,11111.0,7.0,7.0,9647.0,5.0,6.0,25541.0
112,Trote,"3592,6","0,7","5132,285714",8.0,8.0,True,9535.0,9.0,True,...,16564.0,3.0,2.0,34291.0,1.0,0.0,19102.0,2.0,2.0,10206.0

In [11]:
s = "abcde"
s[:-1]

'abcd'

In [7]:
import pandas as pd
df = pd.read_csv('data-polo.csv', sep=',', decimal='.')

In [13]:
for i in range(2,11):
    print(df[f"match-sample-rotate_{i}_user_answer"].head(3))

0    FALSE
1     TRUE
2     TRUE
Name: match-sample-rotate_2_user_answer, dtype: object
0     TRUE
1     TRUE
2    FALSE
Name: match-sample-rotate_3_user_answer, dtype: object
0    FALSE
1     TRUE
2    FALSE
Name: match-sample-rotate_4_user_answer, dtype: object
0     TRUE
1     TRUE
2    FALSE
Name: match-sample-rotate_5_user_answer, dtype: object
0     TRUE
1    FALSE
2    FALSE
Name: match-sample-rotate_6_user_answer, dtype: object
0     TRUE
1     TRUE
2    FALSE
Name: match-sample-rotate_7_user_answer, dtype: object
0     TRUE
1     TRUE
2    FALSE
Name: match-sample-rotate_8_user_answer, dtype: object
0     TRUE
1    FALSE
2    FALSE
Name: match-sample-rotate_9_user_answer, dtype: object
0    FALSE
1     TRUE
2    FALSE
Name: match-sample-rotate_10_user_answer, dtype: object

In [33]:
def prepare_column(df, column):
    if not (str(df[column])=="nan" or str(df[f"{column[:-14]}user_answer"])=="nan"):
        return (str(df[column]).upper() == str(df[f"{column[:-14]}user_answer"]).upper())
    return math.nan

for i in range(2,11):
    new_column = df.apply(prepare_column, axis=1, args=(f"match-sample-rotate_{i}_correct_answer",))
    df[f"match-sample-rotate_{i}_user_score"] = new_column.astype(float)

In [34]:
df.to_csv("complete_data-fixed.csv", index=False, decimal=".")

In [26]:
df["match-sample-rotate_3_user_score"].head(5)

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: match-sample-rotate_3_user_score, dtype: float64

In [24]:
df["match-sample-rotate_3_user_answer"].head(5)

0     TRUE
1     TRUE
2    FALSE
3    FALSE
4    FALSE
Name: match-sample-rotate_3_user_answer, dtype: object

In [25]:
df["match-sample-rotate_3_correct_answer"].head(5)

0     True
1     True
2    False
3    False
4    False
Name: match-sample-rotate_3_correct_answer, dtype: bool